import os
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.tree import Tree
from rich.columns import Columns
from rich.text import Text
from .models import DirectoryNode, ProjectProfile

console = Console()

def format_size(size_bytes: int) -> str:
    """Formats size in bytes to KB, MB, or GB."""
    for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} PB"

def get_confidence_style(confidence: str) -> str:
    """Returns the color style for the confidence level."""
    if confidence.lower() == "high":
        return "bold green"
    elif confidence.lower() == "medium":
        return "bold yellow"
    else:
        return "bold red"

def build_tree(node: DirectoryNode, tree: Tree, current_depth: int = 0) -> None:
    """Recursively builds the rich Tree from DirectoryNode."""
    if current_depth >= 3:
        if node.children:
            tree.add(f"[dim]... {len(node.children)} more items[/dim]")
        return

    for child in node.children:
        if child.is_dir:
            style = "bold blue"
            prefix = "📁 "
            branch = tree.add(f"[{style}]{prefix}{child.name}[/{style}]")
            build_tree(child, branch, current_depth + 1)
        else:
            if child.extension == ".py":
                style = "green"
                prefix = "🐍 "
            elif child.extension in [".js", ".ts", ".jsx", ".tsx"]:
                style = "yellow"
                prefix = "⚡ "
            elif child.extension in [".json", ".toml", ".yaml", ".yml"]:
                style = "magenta"
                prefix = "⚙️ "
            else:
                style = "white"
                prefix = "📄 "

            tree.add(f"[{style}]{prefix}{child.name}[/{style}]")

def render_terminal(node: DirectoryNode, profile: ProjectProfile, explanation: dict) -> None:
    """Renders the stunning terminal output for CodeMappr."""

    # 1. HEADER PANEL
    header_text = Text()
    header_text.append("CodeMappr\n", style="bold bright_cyan")
    header_text.append("Codebase Intelligence\n", style="dim white")

    project_name = os.path.basename(os.path.abspath(profile.root_path))
    header_text.append(project_name, style="yellow")
    console.print(Panel(header_text, expand=True))

    # 2. PROJECT PROFILE PANEL
    profile_table = Table(show_header=False, box=None)
    profile_table.add_row("Type", f"[bold green]{profile.project_type}[/bold green]")
    profile_table.add_row("Stack", f"[cyan]{' · '.join(profile.language_stack)}[/cyan]")
    profile_table.add_row("Framework", profile.framework or "—")
    profile_table.add_row("Total Files", str(profile.total_files))
    profile_table.add_row("Total Dirs", str(profile.total_dirs))
    profile_table.add_row("Size", format_size(profile.total_size_bytes))
    profile_table.add_row("Confidence", f"[{get_confidence_style(profile.confidence)}]{profile.confidence}[/]")
    console.print(Panel(profile_table, title="Project Profile", title_align="left"))

    # 3. SUMMARY PANEL
    summary_text = Text()
    summary_text.append(explanation["summary"] + "\n\n", style="white")
    if explanation["structure"]:
        summary_text.append("Key Folders:\n", style="bold white")
        for folder, purpose in explanation["structure"].items():
            summary_text.append(f"📁 {folder} ", style="white")
            summary_text.append(f"→ {purpose}\n", style="dim italic")
    console.print(Panel(summary_text, title="Architecture Summary", title_align="left"))

    # 4. ENTRY POINTS + NOTABLE FILES
    entry_points_text = Text()
    for ep in explanation["entry_points"]:
        entry_points_text.append(f"▶ {ep}\n", style="green")

    notable_files_text = Text()
    for nf in explanation["notable_files"]:
        notable_files_text.append(f"📄 {nf}\n", style="yellow")

    columns = Columns([
        Panel(entry_points_text, title="Entry Points", title_align="left", expand=True),
        Panel(notable_files_text, title="Notable Files", title_align="left", expand=True)
    ])
    console.print(columns)

    # 5. DIRECTORY TREE PANEL
    tree = Tree(f"[bold blue]📁 {node.name}[/bold blue]")
    build_tree(node, tree)
    console.print(Panel(tree, title="Directory Tree", title_align="left"))

    # 6. FOOTER
    console.print(Text("Generated by CodeMappr v1.0.0 · github.com/yourusername/codemappr", style="dim"), justify="center")
